require 'hyperloop-config'
require 'rails/generators'
require 'hyper-model'

Hyperloop.import 'reactrb/auto-import'
Hyperloop.import 'hyper-router'

require 'generators/hyperloop/install_generator'
require 'generators/hyper/component_generator'
require 'generators/hyper/router_generator'
require 'opal-rails'
require 'react-rails'
require 'hyper-model'
require 'opal-browser'
require 'mini_racer'
require 'hyper-router'
require 'hyperloop/version'
